server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/devlivery_db_dev?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC-6
    username: root
#    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
  application:
    zipkin: http://localhost:9411
    
feign:
  client:
    config:
      default:
        errorDecoder: com.example.delivery.exception.
        loggerLevel: BASIC
#-------------------------------------
# logger configuration
#-------------------------------------
logging:
  level:
    mx.fonyoutelecom: INFO      
resilience4j.circuitbreaker:
    instances:
        productServiceCB:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10 
resilience4j.retry:
    instances:
        productServiceCB:
            maxAttempts: 3
            waitDuration: 10s
            enableExponentialBackoff: true
            exponentialBackoffMultiplier: 2

        