server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} 
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/devlivery_db_dev?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC-6
    username: root
#    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
#-------------------------------------
# Spring configuration
#-------------------------------------

springdoc:
  api-docs:
    enabled: true
    path: /api-docs/**
    paths-to-match: /user/**
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
#-------------------------------------
# logger configuration
#-------------------------------------
logging:
  level:
    mx.fonyoutelecom: INFO       